### ISSUE TITLE
Access token when signed in success with google play services on android

### ISSUE THREAD

**Issue by blake1986** [sdkbox/sdkbox-sample-sdkboxplay#16]
Pls update sdk to retrieve token with return by GoogleSignInAccount after signed in success 

Many tks, I really need this information

**Comment by SdkboxMan** [comment]
You can use this to get the token
```
sdkbox::SdkboxPlay::getPlayerAccountField("server_auth_code")
```

**Comment by yinjimmy** [comment]
@blake1986 

```
sdkbox::SdkboxPlay::getPlayerAccountField("server_auth_code")
```

Whether it meets your needs ?

**Comment by blake1986** [comment]
yes, many thanks for this :)
